### ISSUE TITLE
Install via NPM

### ISSUE THREAD

**Issue by Purus** [quanganh206/ionic2-scrolltabs#2]
Is installation via NPM possible? Currently the docs request to clone the repo and copy the files.

Using NPM to handle this would be great as other ionic libs.

**Comment by quanganh206** [comment]
No, I not support it yet.

**Comment by metodome** [comment]
@ViewChild('scrollTab') scroll: Scroll;
from
this.scroll.scrollElement.scrollLeft
to
this.scroll._scrollContent.nativeElement.scrollLeft

kindly update in git

**Comment by quanganh206** [comment]
Thanks, did not sure where do you clone? I had in git yet for latest update.
